# ========== 阶段 1：安装依赖（跳过 postinstall，避免 fumadocs-mdx 在无配置时报错） ==========
FROM node:20-alpine AS deps
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

# ========== 阶段 2：构建 ==========
# NEXT_PUBLIC_* 在 Next 里是构建时内联的，需在 Dokploy 配置「构建时环境变量」，否则 Analytics/Stripe 等不生效
FROM node:20-alpine AS builder
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ARG NEXT_PUBLIC_DEMO_WEBSITE
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY
ARG NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY
ARG NEXT_PUBLIC_STRIPE_PRICE_LIFETIME
ARG NEXT_PUBLIC_STRIPE_PRICE_CREDITS_BASIC
ARG NEXT_PUBLIC_STRIPE_PRICE_CREDITS_STANDARD
ARG NEXT_PUBLIC_STRIPE_PRICE_CREDITS_PREMIUM
ARG NEXT_PUBLIC_STRIPE_PRICE_CREDITS_ENTERPRISE
ARG NEXT_PUBLIC_UMAMI_WEBSITE_ID
ARG NEXT_PUBLIC_UMAMI_SCRIPT
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_SCRIPT
ARG NEXT_PUBLIC_OPENPANEL_CLIENT_ID
ARG NEXT_PUBLIC_CLARITY_PROJECT_ID
ARG NEXT_PUBLIC_CRISP_WEBSITE_ID
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_SELINE_TOKEN
ARG NEXT_PUBLIC_DATAFAST_DOMAIN
ARG NEXT_PUBLIC_DATAFAST_WEBSITE_ID
ARG NEXT_PUBLIC_AHREFS_WEBSITE_ID
ARG NEXT_PUBLIC_AFFILIATE_PROMOTEKIT_ID
ARG NEXT_PUBLIC_AFFILIATE_AFFONSO_ID
ENV NEXT_TELEMETRY_DISABLED=1
ENV DOCKER_BUILD=true
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
ENV NEXT_PUBLIC_DEMO_WEBSITE=$NEXT_PUBLIC_DEMO_WEBSITE
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY=$NEXT_PUBLIC_STRIPE_PRICE_PRO_MONTHLY
ENV NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY=$NEXT_PUBLIC_STRIPE_PRICE_PRO_YEARLY
ENV NEXT_PUBLIC_STRIPE_PRICE_LIFETIME=$NEXT_PUBLIC_STRIPE_PRICE_LIFETIME
ENV NEXT_PUBLIC_STRIPE_PRICE_CREDITS_BASIC=$NEXT_PUBLIC_STRIPE_PRICE_CREDITS_BASIC
ENV NEXT_PUBLIC_STRIPE_PRICE_CREDITS_STANDARD=$NEXT_PUBLIC_STRIPE_PRICE_CREDITS_STANDARD
ENV NEXT_PUBLIC_STRIPE_PRICE_CREDITS_PREMIUM=$NEXT_PUBLIC_STRIPE_PRICE_CREDITS_PREMIUM
ENV NEXT_PUBLIC_STRIPE_PRICE_CREDITS_ENTERPRISE=$NEXT_PUBLIC_STRIPE_PRICE_CREDITS_ENTERPRISE
ENV NEXT_PUBLIC_UMAMI_WEBSITE_ID=$NEXT_PUBLIC_UMAMI_WEBSITE_ID
ENV NEXT_PUBLIC_UMAMI_SCRIPT=$NEXT_PUBLIC_UMAMI_SCRIPT
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST
ENV NEXT_PUBLIC_PLAUSIBLE_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_DOMAIN
ENV NEXT_PUBLIC_PLAUSIBLE_SCRIPT=$NEXT_PUBLIC_PLAUSIBLE_SCRIPT
ENV NEXT_PUBLIC_OPENPANEL_CLIENT_ID=$NEXT_PUBLIC_OPENPANEL_CLIENT_ID
ENV NEXT_PUBLIC_CLARITY_PROJECT_ID=$NEXT_PUBLIC_CLARITY_PROJECT_ID
ENV NEXT_PUBLIC_CRISP_WEBSITE_ID=$NEXT_PUBLIC_CRISP_WEBSITE_ID
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_SELINE_TOKEN=$NEXT_PUBLIC_SELINE_TOKEN
ENV NEXT_PUBLIC_DATAFAST_DOMAIN=$NEXT_PUBLIC_DATAFAST_DOMAIN
ENV NEXT_PUBLIC_DATAFAST_WEBSITE_ID=$NEXT_PUBLIC_DATAFAST_WEBSITE_ID
ENV NEXT_PUBLIC_AHREFS_WEBSITE_ID=$NEXT_PUBLIC_AHREFS_WEBSITE_ID
ENV NEXT_PUBLIC_AFFILIATE_PROMOTEKIT_ID=$NEXT_PUBLIC_AFFILIATE_PROMOTEKIT_ID
ENV NEXT_PUBLIC_AFFILIATE_AFFONSO_ID=$NEXT_PUBLIC_AFFILIATE_AFFONSO_ID
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm run postinstall
RUN pnpm build

# ========== 阶段 3：运行 ==========
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
